// Product Seed Script for Glow Naturals
// Run this script to populate Firestore products collection
// Usage: node scripts/seedProducts.js

import { initializeApp } from 'firebase/app';
import { getFirestore, doc, serverTimestamp, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDVF6vz1RgFB51Q9b6Zb77H-dNOZrLqhsg",
  authDomain: "beautyproducts-285a5.firebaseapp.com",
  projectId: "beautyproducts-285a5",
  storageBucket: "beautyproducts-285a5.firebasestorage.app",
  messagingSenderId: "673318882675",
  appId: "1:673318882675:web:d71324ce8fe57c23ad0906",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

function slugify(value) {
  return String(value || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Helper function to create/update product (B2C fields only)
async function createProduct(product) {
  try {
    const productId = `${slugify(product.category)}-${slugify(product.name)}`;
    await setDoc(
      doc(db, 'products', productId),
      {
        name: product.name,
        description: product.description,
        category: product.category,
        retailPrice: Number(product.retailPrice || 0),
        stock: Number(product.stock || 0),
        bestseller: Boolean(product.bestseller),
        imageUrl: product.imageUrl || '',
        createdAt: serverTimestamp(),
      },
      { merge: true },
    );
    console.log(`Added/updated: ${product.name} (${productId})`);
    return productId;
  } catch (error) {
    console.error(`Error adding ${product.name}:`, error.message);
    return null;
  }
}
// Healthcare Products
const healthcareProducts = [
  // Men's Wellness Kit
  {
    name: 'Shilayu Capsule',
    description: 'Men\'s wellness supplement - 20 capsules',
    category: "Men's Wellness",
    retailPrice: 450,
    bulkPrice: 400,
    minBulkQty: 10,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Ayuvanta Capsule',
    description: 'Men\'s wellness supplement - 60 capsules',
    category: "Men's Wellness",
    retailPrice: 499,
    bulkPrice: 450,
    minBulkQty: 10,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Female's Wellness Kit
  {
    name: 'Femoyu Syrup',
    description: 'Female wellness syrup - 500 ml',
    category: "Female's Wellness",
    retailPrice: 499,
    bulkPrice: 450,
    minBulkQty: 10,
    stock: 50,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Femoyu Tablet',
    description: 'Female wellness tablets - 60 tablets',
    category: "Female's Wellness",
    retailPrice: 499,
    bulkPrice: 450,
    minBulkQty: 10,
    stock: 50,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Thyroid Potali',
    description: 'Thyroid care herbal powder',
    category: "Female's Wellness",
    retailPrice: 100,
    bulkPrice: 90,
    minBulkQty: 20,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Joint Care Kit
  {
    name: 'Joint Pain Potali',
    description: 'Herbal powder for joint care',
    category: 'Joint Care',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Joint Pain Oil',
    description: 'Therapeutic oil for joint pain relief - 100 ml',
    category: 'Joint Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 50,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Joint Pain Lep',
    description: 'Herbal paste for joint care - 100 gm',
    category: 'Joint Care',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Arthoyu Capsule',
    description: 'Joint care capsules - 60 capsules',
    category: 'Joint Care',
    retailPrice: 499,
    bulkPrice: 450,
    minBulkQty: 10,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Bonowin Tablet',
    description: 'Bone health tablets - 60 tablets',
    category: 'Joint Care',
    retailPrice: 340,
    bulkPrice: 310,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Weight Loss Kit
  {
    name: 'Trikatu Churn',
    description: 'Weight management powder - 100 gm',
    category: 'Weight Loss',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Trimoyu Syrup',
    description: 'Weight management syrup - 500 ml',
    category: 'Weight Loss',
    retailPrice: 499,
    bulkPrice: 450,
    minBulkQty: 10,
    stock: 50,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Greenzo Pro Effervescent',
    description: 'Weight management effervescent tablets - 15 tablets',
    category: 'Weight Loss',
    retailPrice: 325,
    bulkPrice: 295,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Collagen Effervescent',
    description: 'Collagen supplement effervescent tablets - 15 tablets',
    category: 'Weight Loss',
    retailPrice: 325,
    bulkPrice: 295,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Piles Care Kit
  {
    name: 'Lexocare Powder',
    description: 'Piles care powder - 100 gm',
    category: 'Piles Care',
    retailPrice: 350,
    bulkPrice: 320,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Anoact Vati',
    description: 'Piles care tablets - 60 tablets',
    category: 'Piles Care',
    retailPrice: 330,
    bulkPrice: 300,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Anoact Ointment',
    description: 'Piles care ointment - 20 gm',
    category: 'Piles Care',
    retailPrice: 190,
    bulkPrice: 170,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Fungal Infection / Psoriasis / Skin Infection / Eczema Kit
  {
    name: 'Eczact Ointment',
    description: 'Eczema and skin infection ointment - 20 gm',
    category: 'Skin Care',
    retailPrice: 220,
    bulkPrice: 200,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Gandhak Rasayan',
    description: 'Skin health tablets - 60 tablets',
    category: 'Skin Care',
    retailPrice: 330,
    bulkPrice: 300,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Kidney Support Kit
  {
    name: 'Gokshur Bharad',
    description: 'Kidney support powder - 100 gm',
    category: 'Kidney Support',
    retailPrice: 240,
    bulkPrice: 220,
    minBulkQty: 15,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Gokshu Pro',
    description: 'Kidney support tablets - 60 tablets',
    category: 'Kidney Support',
    retailPrice: 330,
    bulkPrice: 300,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Cardiac Care
  {
    name: 'Arujvita Tablet',
    description: 'Cardiac care tablets - 60 tablets',
    category: 'Cardiac Care',
    retailPrice: 390,
    bulkPrice: 350,
    minBulkQty: 10,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Skin Care
  {
    name: 'Skinotox Tablet',
    description: 'Skin detox tablets - 60 tablets',
    category: 'Skin Care',
    retailPrice: 330,
    bulkPrice: 300,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Hair Care
  {
    name: 'Sukesha Tablet',
    description: 'Hair care tablets - 60 tablets',
    category: 'Hair Care',
    retailPrice: 330,
    bulkPrice: 300,
    minBulkQty: 12,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
  // Diabetes Care
  {
    name: 'Meharium Tablet',
    description: 'Diabetes care tablets - 60 tablets',
    category: 'Diabetes Care',
    retailPrice: 390,
    bulkPrice: 350,
    minBulkQty: 10,
    stock: 50,
    bestseller: false,
    imageUrl: '',
  },
];

// Skin & Hair Care Products
const skinHairProducts = [
  // Soaps
  {
    name: 'Haldi Chandan Soap',
    description: 'Turmeric and sandalwood soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Rice Potato Soap',
    description: 'Rice and potato soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Neem Soap',
    description: 'Neem antibacterial soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Papaya Soap',
    description: 'Papaya brightening soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Bridal Soap',
    description: 'Bridal glow soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Double Layer D-tan Soap',
    description: 'Double layer tan removal soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Almond Milk Soap',
    description: 'Almond milk nourishing soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Rose Milk Soap',
    description: 'Rose milk soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Charcoal Soap',
    description: 'Activated charcoal soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Honey Milk Soap',
    description: 'Honey milk soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Saffron Milk Soap',
    description: 'Saffron milk soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Goat Milk Soap',
    description: 'Goat milk soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Ubtan Soap',
    description: 'Ubtan traditional soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Dark Spot Soap',
    description: 'Dark spot removal soap - 80 gm',
    category: 'Soap',
    retailPrice: 100,
    bulkPrice: 85,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Saffron Milk Facial Bomb',
    description: 'Saffron milk facial bomb - 10 gm',
    category: 'Soap',
    retailPrice: 30,
    bulkPrice: 25,
    minBulkQty: 50,
    stock: 200,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Charcoal Facial Bomb',
    description: 'Charcoal facial bomb - 10 gm',
    category: 'Soap',
    retailPrice: 30,
    bulkPrice: 25,
    minBulkQty: 50,
    stock: 200,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Honey Milk Facial Bomb',
    description: 'Honey milk facial bomb - 10 gm',
    category: 'Soap',
    retailPrice: 30,
    bulkPrice: 25,
    minBulkQty: 50,
    stock: 200,
    bestseller: false,
    imageUrl: '',
  },
  // Face Wash
  {
    name: 'Haldi Chandan Facewash',
    description: 'Turmeric and sandalwood facewash - 60 ml',
    category: 'Face Wash',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Neem Facewash',
    description: 'Neem antibacterial facewash - 60 ml',
    category: 'Face Wash',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Coffee Facewash',
    description: 'Coffee exfoliating facewash - 60 ml',
    category: 'Face Wash',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Charcoal Facewash',
    description: 'Activated charcoal facewash - 60 ml',
    category: 'Face Wash',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Green Tea Facewash',
    description: 'Green tea facewash - 60 ml',
    category: 'Face Wash',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Lip Care Products
  {
    name: 'Lipbalm',
    description: 'Herbal lip balm - 15 gm',
    category: 'Lip Care',
    retailPrice: 120,
    bulkPrice: 110,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Lipscrub',
    description: 'Herbal lip scrub - 35 gm',
    category: 'Lip Care',
    retailPrice: 150,
    bulkPrice: 135,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Hair Products
  {
    name: 'Hair Oil',
    description: 'Herbal hair oil - 100 ml',
    category: 'Hair Care',
    retailPrice: 280,
    bulkPrice: 250,
    minBulkQty: 10,
    stock: 60,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Hair Shampoo',
    description: 'Herbal hair shampoo - 100 ml',
    category: 'Hair Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 70,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Hair Conditioner',
    description: 'Herbal hair conditioner - 100 gm',
    category: 'Hair Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 70,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Pack',
    description: 'Herbal hair pack - 100 gm',
    category: 'Hair Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 70,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Tonic',
    description: 'Hair growth tonic - 100 ml',
    category: 'Hair Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 70,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Serum',
    description: 'Hair serum - 100 ml',
    category: 'Hair Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 70,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Dye (Black)',
    description: 'Herbal hair dye - Black - 100 gm',
    category: 'Hair Care',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Dye (Brown)',
    description: 'Herbal hair dye - Brown - 100 gm',
    category: 'Hair Care',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Skin Care Products
  {
    name: 'Herbal Face Pack',
    description: 'Herbal face pack - 70 gm',
    category: 'Skin Care',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Coffee Honey Scrub',
    description: 'Coffee honey exfoliating scrub - 70 gm',
    category: 'Skin Care',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Aloevera Gel',
    description: 'Pure aloe vera gel - 70 gm',
    category: 'Skin Care',
    retailPrice: 160,
    bulkPrice: 145,
    minBulkQty: 15,
    stock: 80,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Kumkumadi Oil',
    description: 'Kumkumadi face oil - 15 ml',
    category: 'Skin Care',
    retailPrice: 225,
    bulkPrice: 200,
    minBulkQty: 12,
    stock: 60,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Saffron Glow Gel',
    description: 'Saffron glow gel - 25 gm',
    category: 'Skin Care',
    retailPrice: 225,
    bulkPrice: 200,
    minBulkQty: 12,
    stock: 60,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Saffron Night Cream',
    description: 'Saffron night cream - 10 gm',
    category: 'Skin Care',
    retailPrice: 325,
    bulkPrice: 295,
    minBulkQty: 10,
    stock: 50,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'Anti-acne Gel',
    description: 'Anti-acne treatment gel - 25 gm',
    category: 'Skin Care',
    retailPrice: 225,
    bulkPrice: 200,
    minBulkQty: 12,
    stock: 60,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Rose Toner',
    description: 'Rose face toner - 100 ml',
    category: 'Skin Care',
    retailPrice: 150,
    bulkPrice: 135,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Sunscreen',
    description: 'Herbal sunscreen - 20 gm',
    category: 'Skin Care',
    retailPrice: 225,
    bulkPrice: 200,
    minBulkQty: 12,
    stock: 60,
    bestseller: true,
    imageUrl: '',
  },
  {
    name: 'HD Makeup Powder',
    description: 'HD makeup powder - 20 gm',
    category: 'Skin Care',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 60,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Kajal',
    description: 'Herbal kajal - 8 gm',
    category: 'Skin Care',
    retailPrice: 175,
    bulkPrice: 160,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Other Products
  {
    name: 'Eyebrow Growth Oil',
    description: 'Eyebrow growth oil - 15 ml',
    category: 'Other',
    retailPrice: 120,
    bulkPrice: 110,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Cracked Heel Repair Cream',
    description: 'Cracked heel repair cream - 70 gm',
    category: 'Other',
    retailPrice: 150,
    bulkPrice: 135,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Underarm Depigmentation Deostick',
    description: 'Underarm depigmentation deostick',
    category: 'Other',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 60,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Bath Salt',
    description: 'Herbal bath salt - 100 gm',
    category: 'Other',
    retailPrice: 150,
    bulkPrice: 135,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Herbal Tooth Powder',
    description: 'Herbal tooth powder - 100 gm',
    category: 'Other',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Amrutdhara',
    description: 'Amrutdhara - 10 ml',
    category: 'Other',
    retailPrice: 150,
    bulkPrice: 135,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Hair Removal Cream',
    description: 'Herbal hair removal cream - 100 gm',
    category: 'Other',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Winter Kit
  {
    name: 'Moisturizer',
    description: 'Herbal moisturizer - 50 gm',
    category: 'Winter Kit',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 60,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Body Butter',
    description: 'Herbal body butter - 50 gm',
    category: 'Winter Kit',
    retailPrice: 250,
    bulkPrice: 225,
    minBulkQty: 12,
    stock: 60,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Depigmentation Lipbalm',
    description: 'Depigmentation lip balm - 5 gm',
    category: 'Winter Kit',
    retailPrice: 200,
    bulkPrice: 180,
    minBulkQty: 15,
    stock: 80,
    bestseller: false,
    imageUrl: '',
  },
  // Abhyang Bath Kit
  {
    name: 'Abhyang Oil',
    description: 'Abhyang massage oil - 50 ml',
    category: 'Bath Kit',
    retailPrice: 100,
    bulkPrice: 90,
    minBulkQty: 20,
    stock: 100,
    bestseller: false,
    imageUrl: '',
  },
  {
    name: 'Shahi Ubtan',
    description: 'Shahi ubtan powder - 25 gm',
    category: 'Bath Kit',
    retailPrice: 30,
    bulkPrice: 25,
    minBulkQty: 50,
    stock: 200,
    bestseller: false,
    imageUrl: '',
  },
];

// Main seeding function
async function seedProducts() {
  console.log('Starting product seeding...\n');
  
  const allProducts = [...healthcareProducts, ...skinHairProducts];
  let successCount = 0;
  let failCount = 0;

  for (const product of allProducts) {
    const id = await createProduct(product);
    if (id) {
      successCount++;
    } else {
      failCount++;
    }
    // Small delay to avoid overwhelming Firestore
    await new Promise(resolve => setTimeout(resolve, 100));
  }

  console.log(`\n✅ Seeding complete!`);
  console.log(`   Success: ${successCount} products`);
  console.log(`   Failed: ${failCount} products`);
  console.log(`   Total: ${allProducts.length} products`);
}

// Run the seed
seedProducts()
  .then(() => {
    console.log('\nDone.');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\nFatal error:', error);
    process.exit(1);
  });



